alias act="cd /mnt/c/Users/Leon/OneDrive/projekti_2021/3-autoCUT\ \(live\)/"
alias dt="cd /mnt/c/Users/Leon/Desktop"
alias osn="cd /mnt/c/Users/Leon/OneDrive/Dokumenti/06-osnovna"
alias fila="cd /mnt/c/Users/Leon/OneDrive/projekti_2023/34-printing\ filament\ manufacturing"
alias todo="vim /mnt/c/Users/Leon/OneDrive/IntisEngineering/ie.todo.md"
alias eks="vim /mnt/c/Users/Leon.hergesic.adamov/OneDrive/projekti_2023/34-printing\ filament\ manufacturing/eks.todo.md"
